on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Restore dependencies
        run: dotnet restore ./MeteoApi/MeteoApi.csproj
      - name: Build
        run: dotnet build ./MeteoApi/MeteoApi.csproj --no-restore
      - name: Test
        run: dotnet test ./MeteoApi.Tests/MeteoApi.Tests.csproj
        
    
